import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/Header";

import { Poppins } from 'next/font/google';


import "./globals.css";

const poppins = Poppins({ subsets: ['latin'], weight: "400" });
export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_COMPANY_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <SessionProvider>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
